//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.GateCardServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://anvien.vn/", ConfigurationName="GateCardServices.WsGateCardSoap")]
    public interface WsGateCardSoap {
        
        // CODEGEN: Generating message contract since message CardInputSandboxRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://anvien.vn/CardInputSandbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Web.GateCardServices.CardInputSandboxResponse CardInputSandbox(Web.GateCardServices.CardInputSandboxRequest request);
        
        // CODEGEN: Generating message contract since message CardInputLiveRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://anvien.vn/CardInputLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Web.GateCardServices.CardInputLiveResponse CardInputLive(Web.GateCardServices.CardInputLiveRequest request);
        
        // CODEGEN: Generating message contract since message TopupCardRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://anvien.vn/TopupCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Web.GateCardServices.TopupCardResponse TopupCard(Web.GateCardServices.TopupCardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anvien.vn/")]
    public partial class AuthenSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anvien.vn/")]
    public partial class CardResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string transIdField;
        
        private string amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransId {
            get {
                return this.transIdField;
            }
            set {
                this.transIdField = value;
                this.RaisePropertyChanged("TransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardInputSandbox", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class CardInputSandboxRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://anvien.vn/")]
        public Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=1)]
        public string cardSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=2)]
        public string cardPin;
        
        public CardInputSandboxRequest() {
        }
        
        public CardInputSandboxRequest(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            this.AuthenSoapHeader = AuthenSoapHeader;
            this.serviceName = serviceName;
            this.cardSerial = cardSerial;
            this.cardPin = cardPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardInputSandboxResponse", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class CardInputSandboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public Web.GateCardServices.CardResponse CardInputSandboxResult;
        
        public CardInputSandboxResponse() {
        }
        
        public CardInputSandboxResponse(Web.GateCardServices.CardResponse CardInputSandboxResult) {
            this.CardInputSandboxResult = CardInputSandboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardInputLive", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class CardInputLiveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://anvien.vn/")]
        public Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=1)]
        public string cardSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=2)]
        public string cardPin;
        
        public CardInputLiveRequest() {
        }
        
        public CardInputLiveRequest(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            this.AuthenSoapHeader = AuthenSoapHeader;
            this.serviceName = serviceName;
            this.cardSerial = cardSerial;
            this.cardPin = cardPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardInputLiveResponse", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class CardInputLiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public Web.GateCardServices.CardResponse CardInputLiveResult;
        
        public CardInputLiveResponse() {
        }
        
        public CardInputLiveResponse(Web.GateCardServices.CardResponse CardInputLiveResult) {
            this.CardInputLiveResult = CardInputLiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopupCard", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class TopupCardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://anvien.vn/")]
        public Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public string serviceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=1)]
        public string cardSerial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=2)]
        public string cardPin;
        
        public TopupCardRequest() {
        }
        
        public TopupCardRequest(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            this.AuthenSoapHeader = AuthenSoapHeader;
            this.serviceName = serviceName;
            this.cardSerial = cardSerial;
            this.cardPin = cardPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TopupCardResponse", WrapperNamespace="http://anvien.vn/", IsWrapped=true)]
    public partial class TopupCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://anvien.vn/", Order=0)]
        public Web.GateCardServices.CardResponse TopupCardResult;
        
        public TopupCardResponse() {
        }
        
        public TopupCardResponse(Web.GateCardServices.CardResponse TopupCardResult) {
            this.TopupCardResult = TopupCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsGateCardSoapChannel : Web.GateCardServices.WsGateCardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGateCardSoapClient : System.ServiceModel.ClientBase<Web.GateCardServices.WsGateCardSoap>, Web.GateCardServices.WsGateCardSoap {
        
        public WsGateCardSoapClient() {
        }
        
        public WsGateCardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGateCardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGateCardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGateCardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.GateCardServices.CardInputSandboxResponse Web.GateCardServices.WsGateCardSoap.CardInputSandbox(Web.GateCardServices.CardInputSandboxRequest request) {
            return base.Channel.CardInputSandbox(request);
        }
        
        public Web.GateCardServices.CardResponse CardInputSandbox(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            Web.GateCardServices.CardInputSandboxRequest inValue = new Web.GateCardServices.CardInputSandboxRequest();
            inValue.AuthenSoapHeader = AuthenSoapHeader;
            inValue.serviceName = serviceName;
            inValue.cardSerial = cardSerial;
            inValue.cardPin = cardPin;
            Web.GateCardServices.CardInputSandboxResponse retVal = ((Web.GateCardServices.WsGateCardSoap)(this)).CardInputSandbox(inValue);
            return retVal.CardInputSandboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.GateCardServices.CardInputLiveResponse Web.GateCardServices.WsGateCardSoap.CardInputLive(Web.GateCardServices.CardInputLiveRequest request) {
            return base.Channel.CardInputLive(request);
        }
        
        public Web.GateCardServices.CardResponse CardInputLive(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            Web.GateCardServices.CardInputLiveRequest inValue = new Web.GateCardServices.CardInputLiveRequest();
            inValue.AuthenSoapHeader = AuthenSoapHeader;
            inValue.serviceName = serviceName;
            inValue.cardSerial = cardSerial;
            inValue.cardPin = cardPin;
            Web.GateCardServices.CardInputLiveResponse retVal = ((Web.GateCardServices.WsGateCardSoap)(this)).CardInputLive(inValue);
            return retVal.CardInputLiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.GateCardServices.TopupCardResponse Web.GateCardServices.WsGateCardSoap.TopupCard(Web.GateCardServices.TopupCardRequest request) {
            return base.Channel.TopupCard(request);
        }
        
        public Web.GateCardServices.CardResponse TopupCard(Web.GateCardServices.AuthenSoapHeader AuthenSoapHeader, string serviceName, string cardSerial, string cardPin) {
            Web.GateCardServices.TopupCardRequest inValue = new Web.GateCardServices.TopupCardRequest();
            inValue.AuthenSoapHeader = AuthenSoapHeader;
            inValue.serviceName = serviceName;
            inValue.cardSerial = cardSerial;
            inValue.cardPin = cardPin;
            Web.GateCardServices.TopupCardResponse retVal = ((Web.GateCardServices.WsGateCardSoap)(this)).TopupCard(inValue);
            return retVal.TopupCardResult;
        }
    }
}
