//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Banknet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pgWebservices", ConfigurationName="Banknet.PaymentGatewayPortType")]
    public interface PaymentGatewayPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:QuerryBillStatus", ReplyAction="urn:QuerryBillStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.Banknet.QuerryBillStatusResponse QuerryBillStatus(Web.Banknet.QuerryBillStatusRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConfirmTransactionResult", ReplyAction="urn:ConfirmTransactionResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.Banknet.ConfirmTransactionResultResponse ConfirmTransactionResult(Web.Banknet.ConfirmTransactionResultRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Send_GoodInfo_Ext2", ReplyAction="urn:Send_GoodInfo_Ext2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.Banknet.Send_GoodInfo_Ext2Response Send_GoodInfo_Ext2(Web.Banknet.Send_GoodInfo_Ext2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Send_GoodInfo", ReplyAction="urn:Send_GoodInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.Banknet.Send_GoodInfoResponse Send_GoodInfo(Web.Banknet.Send_GoodInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Send_GoodInfo_Ext", ReplyAction="urn:Send_GoodInfo_ExtResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.Banknet.Send_GoodInfo_ExtResponse Send_GoodInfo_Ext(Web.Banknet.Send_GoodInfo_ExtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuerryBillStatus", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class QuerryBillStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_key;
        
        public QuerryBillStatusRequest() {
        }
        
        public QuerryBillStatusRequest(string Merchant_trans_id, string Trans_id, string Merchant_code, string Trans_key) {
            this.Merchant_trans_id = Merchant_trans_id;
            this.Trans_id = Trans_id;
            this.Merchant_code = Merchant_code;
            this.Trans_key = Trans_key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuerryBillStatusResponse", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class QuerryBillStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public QuerryBillStatusResponse() {
        }
        
        public QuerryBillStatusResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmTransactionResult", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class ConfirmTransactionResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_key;
        
        public ConfirmTransactionResultRequest() {
        }
        
        public ConfirmTransactionResultRequest(string Merchant_trans_id, string Trans_id, string Merchant_code, string Trans_result, string Trans_key) {
            this.Merchant_trans_id = Merchant_trans_id;
            this.Trans_id = Trans_id;
            this.Merchant_code = Merchant_code;
            this.Trans_result = Trans_result;
            this.Trans_key = Trans_key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmTransactionResultResponse", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class ConfirmTransactionResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConfirmTransactionResultResponse() {
        }
        
        public ConfirmTransactionResultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfo_Ext2", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfo_Ext2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Good_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Xml_description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Net_cost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ship_fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_fail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string selected_bank;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string service_code;
        
        public Send_GoodInfo_Ext2Request() {
        }
        
        public Send_GoodInfo_Ext2Request(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key, string selected_bank, string service_code) {
            this.Merchant_trans_id = Merchant_trans_id;
            this.Merchant_code = Merchant_code;
            this.Country_code = Country_code;
            this.Good_code = Good_code;
            this.Xml_description = Xml_description;
            this.Net_cost = Net_cost;
            this.Ship_fee = Ship_fee;
            this.Tax = Tax;
            this.Url_success = Url_success;
            this.Url_fail = Url_fail;
            this.Trans_key = Trans_key;
            this.selected_bank = selected_bank;
            this.service_code = service_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfo_Ext2Response", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfo_Ext2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public Send_GoodInfo_Ext2Response() {
        }
        
        public Send_GoodInfo_Ext2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfo", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Good_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Xml_description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Net_cost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ship_fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_fail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_key;
        
        public Send_GoodInfoRequest() {
        }
        
        public Send_GoodInfoRequest(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key) {
            this.Merchant_trans_id = Merchant_trans_id;
            this.Merchant_code = Merchant_code;
            this.Country_code = Country_code;
            this.Good_code = Good_code;
            this.Xml_description = Xml_description;
            this.Net_cost = Net_cost;
            this.Ship_fee = Ship_fee;
            this.Tax = Tax;
            this.Url_success = Url_success;
            this.Url_fail = Url_fail;
            this.Trans_key = Trans_key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfoResponse", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public Send_GoodInfoResponse() {
        }
        
        public Send_GoodInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfo_Ext", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfo_ExtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Merchant_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Good_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Xml_description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Net_cost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ship_fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_success;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url_fail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Trans_key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string selected_bank;
        
        public Send_GoodInfo_ExtRequest() {
        }
        
        public Send_GoodInfo_ExtRequest(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key, string selected_bank) {
            this.Merchant_trans_id = Merchant_trans_id;
            this.Merchant_code = Merchant_code;
            this.Country_code = Country_code;
            this.Good_code = Good_code;
            this.Xml_description = Xml_description;
            this.Net_cost = Net_cost;
            this.Ship_fee = Ship_fee;
            this.Tax = Tax;
            this.Url_success = Url_success;
            this.Url_fail = Url_fail;
            this.Trans_key = Trans_key;
            this.selected_bank = selected_bank;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send_GoodInfo_ExtResponse", WrapperNamespace="http://pgWebservices", IsWrapped=true)]
    public partial class Send_GoodInfo_ExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pgWebservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public Send_GoodInfo_ExtResponse() {
        }
        
        public Send_GoodInfo_ExtResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentGatewayPortTypeChannel : Web.Banknet.PaymentGatewayPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewayPortTypeClient : System.ServiceModel.ClientBase<Web.Banknet.PaymentGatewayPortType>, Web.Banknet.PaymentGatewayPortType {
        
        public PaymentGatewayPortTypeClient() {
        }
        
        public PaymentGatewayPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewayPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Banknet.QuerryBillStatusResponse Web.Banknet.PaymentGatewayPortType.QuerryBillStatus(Web.Banknet.QuerryBillStatusRequest request) {
            return base.Channel.QuerryBillStatus(request);
        }
        
        public string QuerryBillStatus(string Merchant_trans_id, string Trans_id, string Merchant_code, string Trans_key) {
            Web.Banknet.QuerryBillStatusRequest inValue = new Web.Banknet.QuerryBillStatusRequest();
            inValue.Merchant_trans_id = Merchant_trans_id;
            inValue.Trans_id = Trans_id;
            inValue.Merchant_code = Merchant_code;
            inValue.Trans_key = Trans_key;
            Web.Banknet.QuerryBillStatusResponse retVal = ((Web.Banknet.PaymentGatewayPortType)(this)).QuerryBillStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Banknet.ConfirmTransactionResultResponse Web.Banknet.PaymentGatewayPortType.ConfirmTransactionResult(Web.Banknet.ConfirmTransactionResultRequest request) {
            return base.Channel.ConfirmTransactionResult(request);
        }
        
        public string ConfirmTransactionResult(string Merchant_trans_id, string Trans_id, string Merchant_code, string Trans_result, string Trans_key) {
            Web.Banknet.ConfirmTransactionResultRequest inValue = new Web.Banknet.ConfirmTransactionResultRequest();
            inValue.Merchant_trans_id = Merchant_trans_id;
            inValue.Trans_id = Trans_id;
            inValue.Merchant_code = Merchant_code;
            inValue.Trans_result = Trans_result;
            inValue.Trans_key = Trans_key;
            Web.Banknet.ConfirmTransactionResultResponse retVal = ((Web.Banknet.PaymentGatewayPortType)(this)).ConfirmTransactionResult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Banknet.Send_GoodInfo_Ext2Response Web.Banknet.PaymentGatewayPortType.Send_GoodInfo_Ext2(Web.Banknet.Send_GoodInfo_Ext2Request request) {
            return base.Channel.Send_GoodInfo_Ext2(request);
        }
        
        public string Send_GoodInfo_Ext2(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key, string selected_bank, string service_code) {
            Web.Banknet.Send_GoodInfo_Ext2Request inValue = new Web.Banknet.Send_GoodInfo_Ext2Request();
            inValue.Merchant_trans_id = Merchant_trans_id;
            inValue.Merchant_code = Merchant_code;
            inValue.Country_code = Country_code;
            inValue.Good_code = Good_code;
            inValue.Xml_description = Xml_description;
            inValue.Net_cost = Net_cost;
            inValue.Ship_fee = Ship_fee;
            inValue.Tax = Tax;
            inValue.Url_success = Url_success;
            inValue.Url_fail = Url_fail;
            inValue.Trans_key = Trans_key;
            inValue.selected_bank = selected_bank;
            inValue.service_code = service_code;
            Web.Banknet.Send_GoodInfo_Ext2Response retVal = ((Web.Banknet.PaymentGatewayPortType)(this)).Send_GoodInfo_Ext2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Banknet.Send_GoodInfoResponse Web.Banknet.PaymentGatewayPortType.Send_GoodInfo(Web.Banknet.Send_GoodInfoRequest request) {
            return base.Channel.Send_GoodInfo(request);
        }
        
        public string Send_GoodInfo(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key) {
            Web.Banknet.Send_GoodInfoRequest inValue = new Web.Banknet.Send_GoodInfoRequest();
            inValue.Merchant_trans_id = Merchant_trans_id;
            inValue.Merchant_code = Merchant_code;
            inValue.Country_code = Country_code;
            inValue.Good_code = Good_code;
            inValue.Xml_description = Xml_description;
            inValue.Net_cost = Net_cost;
            inValue.Ship_fee = Ship_fee;
            inValue.Tax = Tax;
            inValue.Url_success = Url_success;
            inValue.Url_fail = Url_fail;
            inValue.Trans_key = Trans_key;
            Web.Banknet.Send_GoodInfoResponse retVal = ((Web.Banknet.PaymentGatewayPortType)(this)).Send_GoodInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.Banknet.Send_GoodInfo_ExtResponse Web.Banknet.PaymentGatewayPortType.Send_GoodInfo_Ext(Web.Banknet.Send_GoodInfo_ExtRequest request) {
            return base.Channel.Send_GoodInfo_Ext(request);
        }
        
        public string Send_GoodInfo_Ext(string Merchant_trans_id, string Merchant_code, string Country_code, string Good_code, string Xml_description, string Net_cost, string Ship_fee, string Tax, string Url_success, string Url_fail, string Trans_key, string selected_bank) {
            Web.Banknet.Send_GoodInfo_ExtRequest inValue = new Web.Banknet.Send_GoodInfo_ExtRequest();
            inValue.Merchant_trans_id = Merchant_trans_id;
            inValue.Merchant_code = Merchant_code;
            inValue.Country_code = Country_code;
            inValue.Good_code = Good_code;
            inValue.Xml_description = Xml_description;
            inValue.Net_cost = Net_cost;
            inValue.Ship_fee = Ship_fee;
            inValue.Tax = Tax;
            inValue.Url_success = Url_success;
            inValue.Url_fail = Url_fail;
            inValue.Trans_key = Trans_key;
            inValue.selected_bank = selected_bank;
            Web.Banknet.Send_GoodInfo_ExtResponse retVal = ((Web.Banknet.PaymentGatewayPortType)(this)).Send_GoodInfo_Ext(inValue);
            return retVal.@return;
        }
    }
}
