//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.WsPayment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.payment.avg.com/", ConfigurationName="WsPayment.WS")]
    public interface WS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.payment.avg.com/WS/getVoucherPaymentInfoRequest", ReplyAction="http://ws.payment.avg.com/WS/getVoucherPaymentInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.WsPayment.getVoucherPaymentInfoResponse getVoucherPaymentInfo(Web.WsPayment.getVoucherPaymentInfoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.payment.avg.com/WS/verifyPaymentRequest", ReplyAction="http://ws.payment.avg.com/WS/verifyPaymentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.WsPayment.verifyPaymentResponse verifyPayment(Web.WsPayment.verifyPaymentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.payment.avg.com/WS/submitVoucherRequest", ReplyAction="http://ws.payment.avg.com/WS/submitVoucherResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Web.WsPayment.submitVoucherResponse submitVoucher(Web.WsPayment.submitVoucherRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.payment.avg.com/")]
    public partial class credential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checksumField;
        
        private string clientIdField;
        
        private string requestTimeField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checksum {
            get {
                return this.checksumField;
            }
            set {
                this.checksumField = value;
                this.RaisePropertyChanged("checksum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
                this.RaisePropertyChanged("requestTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.payment.avg.com/")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseDataField;
        
        private string returnCodeField;
        
        private string returnCodeDescriptionField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("responseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string returnCodeDescription {
            get {
                return this.returnCodeDescriptionField;
            }
            set {
                this.returnCodeDescriptionField = value;
                this.RaisePropertyChanged("returnCodeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVoucherPaymentInfo", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class getVoucherPaymentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Web.WsPayment.credential credential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keySearch;
        
        public getVoucherPaymentInfoRequest() {
        }
        
        public getVoucherPaymentInfoRequest(Web.WsPayment.credential credential, string keySearch) {
            this.credential = credential;
            this.keySearch = keySearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVoucherPaymentInfoResponse", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class getVoucherPaymentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Web.WsPayment.response @return;
        
        public getVoucherPaymentInfoResponse() {
        }
        
        public getVoucherPaymentInfoResponse(Web.WsPayment.response @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyPayment", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class verifyPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transCheckNum;
        
        public verifyPaymentRequest() {
        }
        
        public verifyPaymentRequest(string transCheckNum) {
            this.transCheckNum = transCheckNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyPaymentResponse", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class verifyPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public verifyPaymentResponse() {
        }
        
        public verifyPaymentResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitVoucher", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class submitVoucherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Web.WsPayment.credential credential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceFee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transCheckNum;
        
        public submitVoucherRequest() {
        }
        
        public submitVoucherRequest(Web.WsPayment.credential credential, string subNum, string serviceFee, string transCheckNum) {
            this.credential = credential;
            this.subNum = subNum;
            this.serviceFee = serviceFee;
            this.transCheckNum = transCheckNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitVoucherResponse", WrapperNamespace="http://ws.payment.avg.com/", IsWrapped=true)]
    public partial class submitVoucherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.payment.avg.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Web.WsPayment.response @return;
        
        public submitVoucherResponse() {
        }
        
        public submitVoucherResponse(Web.WsPayment.response @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSChannel : Web.WsPayment.WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClient : System.ServiceModel.ClientBase<Web.WsPayment.WS>, Web.WsPayment.WS {
        
        public WSClient() {
        }
        
        public WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WsPayment.getVoucherPaymentInfoResponse Web.WsPayment.WS.getVoucherPaymentInfo(Web.WsPayment.getVoucherPaymentInfoRequest request) {
            return base.Channel.getVoucherPaymentInfo(request);
        }
        
        public Web.WsPayment.response getVoucherPaymentInfo(Web.WsPayment.credential credential, string keySearch) {
            Web.WsPayment.getVoucherPaymentInfoRequest inValue = new Web.WsPayment.getVoucherPaymentInfoRequest();
            inValue.credential = credential;
            inValue.keySearch = keySearch;
            Web.WsPayment.getVoucherPaymentInfoResponse retVal = ((Web.WsPayment.WS)(this)).getVoucherPaymentInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WsPayment.verifyPaymentResponse Web.WsPayment.WS.verifyPayment(Web.WsPayment.verifyPaymentRequest request) {
            return base.Channel.verifyPayment(request);
        }
        
        public bool verifyPayment(string transCheckNum) {
            Web.WsPayment.verifyPaymentRequest inValue = new Web.WsPayment.verifyPaymentRequest();
            inValue.transCheckNum = transCheckNum;
            Web.WsPayment.verifyPaymentResponse retVal = ((Web.WsPayment.WS)(this)).verifyPayment(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.WsPayment.submitVoucherResponse Web.WsPayment.WS.submitVoucher(Web.WsPayment.submitVoucherRequest request) {
            return base.Channel.submitVoucher(request);
        }
        
        public Web.WsPayment.response submitVoucher(Web.WsPayment.credential credential, string subNum, string serviceFee, string transCheckNum) {
            Web.WsPayment.submitVoucherRequest inValue = new Web.WsPayment.submitVoucherRequest();
            inValue.credential = credential;
            inValue.subNum = subNum;
            inValue.serviceFee = serviceFee;
            inValue.transCheckNum = transCheckNum;
            Web.WsPayment.submitVoucherResponse retVal = ((Web.WsPayment.WS)(this)).submitVoucher(inValue);
            return retVal.@return;
        }
    }
}
