//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServices.ServicePayCard {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePayCard.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Generating message contract since message GetListAnVienCardRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListAnVienCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestServices.ServicePayCard.GetListAnVienCardResponse GetListAnVienCard(TestServices.ServicePayCard.GetListAnVienCardRequest request);
        
        // CODEGEN: Generating message contract since message GetListMobileCardRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListMobileCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestServices.ServicePayCard.GetListMobileCardResponse GetListMobileCard(TestServices.ServicePayCard.GetListMobileCardRequest request);
        
        // CODEGEN: Generating message contract since message GetListSubmitVoucherRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListSubmitVoucher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestServices.ServicePayCard.GetListSubmitVoucherResponse GetListSubmitVoucher(TestServices.ServicePayCard.GetListSubmitVoucherRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitVoucherInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string userIdField;
        
        private int amountField;
        
        private string transIdField;
        
        private string returnCodeField;
        
        private string responseDataField;
        
        private string returnCodeDescriptionField;
        
        private string signatureField;
        
        private System.DateTime createDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransId {
            get {
                return this.transIdField;
            }
            set {
                this.transIdField = value;
                this.RaisePropertyChanged("TransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string responseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("responseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string returnCodeDescription {
            get {
                return this.returnCodeDescriptionField;
            }
            set {
                this.returnCodeDescriptionField = value;
                this.RaisePropertyChanged("returnCodeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GateCardInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string userIdField;
        
        private string transIdField;
        
        private string serviceIDField;
        
        private string serialsIdField;
        
        private string cardIdField;
        
        private string resultIdField;
        
        private int amountField;
        
        private string msgField;
        
        private System.DateTime createDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransId {
            get {
                return this.transIdField;
            }
            set {
                this.transIdField = value;
                this.RaisePropertyChanged("TransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SerialsId {
            get {
                return this.serialsIdField;
            }
            set {
                this.serialsIdField = value;
                this.RaisePropertyChanged("SerialsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
                this.RaisePropertyChanged("CardId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ResultId {
            get {
                return this.resultIdField;
            }
            set {
                this.resultIdField = value;
                this.RaisePropertyChanged("ResultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PayCardInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string userIdField;
        
        private string cardIdField;
        
        private string resulIdField;
        
        private string msgField;
        
        private string resulFullField;
        
        private System.DateTime createDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
                this.RaisePropertyChanged("CardId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResulId {
            get {
                return this.resulIdField;
            }
            set {
                this.resulIdField = value;
                this.RaisePropertyChanged("ResulId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResulFull {
            get {
                return this.resulFullField;
            }
            set {
                this.resulFullField = value;
                this.RaisePropertyChanged("ResulFull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListAnVienCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListAnVienCardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime date1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime date2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int status;
        
        public GetListAnVienCardRequest() {
        }
        
        public GetListAnVienCardRequest(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.date1 = date1;
            this.date2 = date2;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListAnVienCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListAnVienCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PayCardInfo[] GetListAnVienCardResult;
        
        public GetListAnVienCardResponse() {
        }
        
        public GetListAnVienCardResponse(PayCardInfo[] GetListAnVienCardResult) {
            this.GetListAnVienCardResult = GetListAnVienCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListMobileCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListMobileCardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime date1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime date2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int status;
        
        public GetListMobileCardRequest() {
        }
        
        public GetListMobileCardRequest(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.date1 = date1;
            this.date2 = date2;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListMobileCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListMobileCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GateCardInfo[] GetListMobileCardResult;
        
        public GetListMobileCardResponse() {
        }
        
        public GetListMobileCardResponse(GateCardInfo[] GetListMobileCardResult) {
            this.GetListMobileCardResult = GetListMobileCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListSubmitVoucher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListSubmitVoucherRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime date1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime date2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int status;
        
        public GetListSubmitVoucherRequest() {
        }
        
        public GetListSubmitVoucherRequest(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.date1 = date1;
            this.date2 = date2;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListSubmitVoucherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListSubmitVoucherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SubmitVoucherInfo[] GetListSubmitVoucherResult;
        
        public GetListSubmitVoucherResponse() {
        }
        
        public GetListSubmitVoucherResponse(SubmitVoucherInfo[] GetListSubmitVoucherResult) {
            this.GetListSubmitVoucherResult = GetListSubmitVoucherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : TestServices.ServicePayCard.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<TestServices.ServicePayCard.ServicesSoap>, TestServices.ServicePayCard.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServices.ServicePayCard.GetListAnVienCardResponse TestServices.ServicePayCard.ServicesSoap.GetListAnVienCard(TestServices.ServicePayCard.GetListAnVienCardRequest request) {
            return base.Channel.GetListAnVienCard(request);
        }
        
        public PayCardInfo[] GetListAnVienCard(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            TestServices.ServicePayCard.GetListAnVienCardRequest inValue = new TestServices.ServicePayCard.GetListAnVienCardRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.date1 = date1;
            inValue.date2 = date2;
            inValue.status = status;
            TestServices.ServicePayCard.GetListAnVienCardResponse retVal = ((TestServices.ServicePayCard.ServicesSoap)(this)).GetListAnVienCard(inValue);
            return retVal.GetListAnVienCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServices.ServicePayCard.GetListMobileCardResponse TestServices.ServicePayCard.ServicesSoap.GetListMobileCard(TestServices.ServicePayCard.GetListMobileCardRequest request) {
            return base.Channel.GetListMobileCard(request);
        }
        
        public GateCardInfo[] GetListMobileCard(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            TestServices.ServicePayCard.GetListMobileCardRequest inValue = new TestServices.ServicePayCard.GetListMobileCardRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.date1 = date1;
            inValue.date2 = date2;
            inValue.status = status;
            TestServices.ServicePayCard.GetListMobileCardResponse retVal = ((TestServices.ServicePayCard.ServicesSoap)(this)).GetListMobileCard(inValue);
            return retVal.GetListMobileCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServices.ServicePayCard.GetListSubmitVoucherResponse TestServices.ServicePayCard.ServicesSoap.GetListSubmitVoucher(TestServices.ServicePayCard.GetListSubmitVoucherRequest request) {
            return base.Channel.GetListSubmitVoucher(request);
        }
        
        public SubmitVoucherInfo[] GetListSubmitVoucher(TestServices.ServicePayCard.AuthenticationHeader AuthenticationHeader, System.DateTime date1, System.DateTime date2, int status) {
            TestServices.ServicePayCard.GetListSubmitVoucherRequest inValue = new TestServices.ServicePayCard.GetListSubmitVoucherRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.date1 = date1;
            inValue.date2 = date2;
            inValue.status = status;
            TestServices.ServicePayCard.GetListSubmitVoucherResponse retVal = ((TestServices.ServicePayCard.ServicesSoap)(this)).GetListSubmitVoucher(inValue);
            return retVal.GetListSubmitVoucherResult;
        }
    }
}
